name: Build pdfs and create a release

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    tags:
      - "v*"
    paths-ignore:
      - docker-typst/**
      - .github/workflows/build-docker-typst.yaml
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build site with docker
        run: |
          docker build --progress=plain --output type=local,dest=./ .
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          gh release create "$TAG" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${TAG#v}" \
              --generate-notes \
              *.pdf