name: Build base container

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches: [ main ]
    paths:
      - docker-typst/**
      - .github/workflows/build-docker-typst.yaml
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# TODO: Look at multi-platform support: https://andrewlock.net/combining-multiple-docker-images-into-a-multi-arch-image/ , https://github.com/sredevopsorg/multi-arch-docker-github-workflow
# * 1. Build in separate jobs
# * 2. Test images before they are pushed to the registry
# * 3. Merge images into a multi-arch image if all of them pass

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Docker login
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build container with github
        run: |
          docker build --progress=plain --tag ghcr.io/${{ github.repository_owner }}/typst:latest --tag ghcr.io/${{ github.repository_owner }}/typst:${{ github.sha }} docker-typst
      - name: Push container
        run: |
          docker push --all-tags ghcr.io/${{ github.repository_owner }}/typst